version: '3.8'

services:
  meili:
    image: getmeili/meilisearch:v0.29
    container_name: meili
    environment:
      - "MEILI_MASTER_KEY=$MEILI_MASTER_KEY"
      - "MEILI_ENV=$MEILI_ENV"
    expose:
      - "7700"
    volumes:
      - ./meili_data:/meili_data
    networks:
      - clash_search_net

  caddy_server:
    image: caddy:2.6.2-alpine
    restart: unless-stopped
    container_name: caddy_server
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./frontend/dist:/srv
    networks:
      - clash_search_net

networks:
  clash_search_net:
