version: '3.8'

services:
  meili:
    image: getmeili/meilisearch:v0.29
    environment:
      - "MEILI_MASTER_KEY=$MEILI_MASTER_KEY"
    ports:
      - 7700:7700
    volumes:
      - ./meili_data:/meili_data

  webserver:
    image: nginx
    ports:
      - 8000:80
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
